baseURL = "https://iniwach.netlify.app"
languageCode = "ja-jp"
languageName = "Japanese"
defaultContentLanguage = "ja"
title = "いにわの欠け耳"
theme = "robust"

[taxonomies]
tag = "tags"
archive = "archives"


[params.author]
thumbnail = "images/author.jpg"
name = "iniwa"
description = "<p>ゲーム好きです。</p>"
twitter = "https://twitter.com/iniwach"
YouTube = "https://www.youtube.com/channel/UCLaOje60cy_9qPJkB_G-AwA"
Twitch = "https://www.twitch.tv/iniwach"


[params]
description = "気が向いた時に更新します。"
dateformat = "Jan 2, 2006" # Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.
hasCJKLanguage = true
disqusShortname = "iniwanoting"



[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.

